### ISSUE TITLE
Can install on Mac but it doesn't produce audio

### ISSUE THREAD

**Issue by stabbyderg** [haiyaku365/StimmingSignalGenerator#3]
**Describe the bug**
I'm able to install on a Mac but it doesn't produce audio, it doesn't allow you to select a speaker system or an audio API, and there's no plot. (See screenshot)

**To Reproduce**
1. Install Dotnet: https://dotnet.microsoft.com/download
2. brew install openal-soft (this is likely redundant, openallib should already be installed by default on Mac OS, as far as I've read)
3. export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:/usr/local/opt/openal-soft/lib
4. dotnet [path to StimmingSignalGenerator.dll]

**Expected behavior**
I expected audio to come out.

**Screenshots**
https://i.imgur.com/W2m5ufj.png

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.5

**Additional context**

**Comment by haiyaku365** [comment]
There might be ErrorLog<date>.txt file some where near StimmingSignalGenerator.dll

Since I'm not own Mac this will be hard for me to fix this.

**Comment by stabbyderg** [comment]
Not seeing an ErrorLog.txt anywhere nearby, unfortunately!

**Comment by haiyaku365** [comment]
Can you try run [OpenTk.OpenALTest](https://github.com/opentk/opentk/tree/4.0.0-pre9.1/OpenALTest) project?
Require [.NET Core 3.1 SDK](https://dot.net) installed.
```
git clone https://github.com/opentk/opentk.git
cd opentk
git checkout 4.0.0-pre9.1
cd OpenALTest
dotnet run
```

**Comment by stabbyderg** [comment]
```
Hello!
Devices: Built-in Output
All Devices: 
ALError at 'Start': Invalid Value
Attributes: , , , , , 
Vendor: Apple Computer Inc., 
Version: 1.1, 
Renderer: Software, 
Extensions: AL_EXT_OFFSET AL_EXT_LINEAR_DISTANCE AL_EXT_EXPONENT_DISTANCE AL_EXT_float32 AL_EXT_STATIC_BUFFER AL_EXT_SOURCE_NOTIFICATIONS AL_EXT_SOURCE_SPATIALIZATION, 
ALC Version: 1.1, 
ALC Extensions: ALC_EXT_CAPTURE ALC_ENUMERATION_EXT ALC_EXT_MAC_OSX ALC_EXT_ASA ALC_EXT_ASA_DISTORTION ALC_EXT_ASA_ROGER_BEEP
Available devices: 
Available capture devices: 
  Corsair VOID Wireless Gaming Dongle
Unhandled exception. System.TypeInitializationException: The type initializer for 'OpenToolkit.Audio.OpenAL.Extensions.Creative.EFX.EFX' threw an exception.
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'ptr')
   at System.Runtime.InteropServices.Marshal.GetDelegateForFunctionPointer(IntPtr ptr, Type t)
   at System.Runtime.InteropServices.Marshal.GetDelegateForFunctionPointer[TDelegate](IntPtr ptr)
   at OpenToolkit.Audio.OpenAL.ApiContainer`1.LoadDelegate[TDelegate](String name) in /Users/[username]/opentk/src/OpenAL/OpenToolkit.OpenAL/Native/ApiContainer.cs:line 54
   at OpenToolkit.Audio.OpenAL.Extensions.Creative.EFX.EFX..cctor() in /Users/[username]/opentk/src/OpenAL/OpenToolkit.OpenAL/Extensions/Creative.EFX/EFX.cs:line 137
   --- End of inner exception stack trace ---
   at OpenToolkit.Audio.OpenAL.Extensions.Creative.EFX.EFX.IsExtensionPresent(ALDevice device) in /Users/[username]/opentk/src/OpenAL/OpenToolkit.OpenAL/Extensions/Creative.EFX/EFX.cs:line 42
   at OpenToolkit.Audio.OpenAL.ALTest.Main() in /Users/[username]/opentk/OpenALTest/ALTest.cs:line 64
```

**Comment by haiyaku365** [comment]
Can you try replace 
_/opentk/OpenALTest/ALTest.cs:line 21_
`if (d.Contains("OpenAL Soft"))`
with
`if (d.Contains("OpenAL Soft") || d.Contains("Built-in Output"))`
and run again?

**Comment by stabbyderg** [comment]
```
Hello!
Devices: Built-in Output
All Devices: 
ALError at 'Start': Invalid Value
Attributes: , , , , , 
Vendor: Apple Computer Inc., 
Version: 1.1, 
Renderer: Software, 
Extensions: AL_EXT_OFFSET AL_EXT_LINEAR_DISTANCE AL_EXT_EXPONENT_DISTANCE AL_EXT_float32 AL_EXT_STATIC_BUFFER AL_EXT_SOURCE_NOTIFICATIONS AL_EXT_SOURCE_SPATIALIZATION, 
ALC Version: 1.1, 
ALC Extensions: ALC_EXT_CAPTURE ALC_ENUMERATION_EXT ALC_EXT_MAC_OSX ALC_EXT_ASA ALC_EXT_ASA_DISTORTION ALC_EXT_ASA_ROGER_BEEP
Available devices: 
Available capture devices: 
  Corsair VOID Wireless Gaming Dongle
Unhandled exception. System.TypeInitializationException: The type initializer for 'OpenToolkit.Audio.OpenAL.Extensions.Creative.EFX.EFX' threw an exception.
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'ptr')
   at System.Runtime.InteropServices.Marshal.GetDelegateForFunctionPointer(IntPtr ptr, Type t)
   at System.Runtime.InteropServices.Marshal.GetDelegateForFunctionPointer[TDelegate](IntPtr ptr)
   at OpenToolkit.Audio.OpenAL.ApiContainer`1.LoadDelegate[TDelegate](String name) in /Users/[username]/opentk/src/OpenAL/OpenToolkit.OpenAL/Native/ApiContainer.cs:line 54
   at OpenToolkit.Audio.OpenAL.Extensions.Creative.EFX.EFX..cctor() in /Users/[username]/opentk/src/OpenAL/OpenToolkit.OpenAL/Extensions/Creative.EFX/EFX.cs:line 137
   --- End of inner exception stack trace ---
   at OpenToolkit.Audio.OpenAL.Extensions.Creative.EFX.EFX.IsExtensionPresent(ALDevice device) in /Users/[username]/opentk/src/OpenAL/OpenToolkit.OpenAL/Extensions/Creative.EFX/EFX.cs:line 42
   at OpenToolkit.Audio.OpenAL.ALTest.Main() in /Users/[username]/opentk/OpenALTest/ALTest.cs:line 64

```

**Comment by haiyaku365** [comment]
https://github.com/kcat/openal-soft/issues/179

Have you try Mac built-in OpenAL.framework before install openal-soft?

**Comment by stabbyderg** [comment]
Uninstalling openal-soft leads to:

```
Hello!
Devices: Built-in Output
All Devices: 
ALError at 'Start': Invalid Value
Attributes: , , , , , 
Vendor: Apple Computer Inc., 
Version: 1.1, 
Renderer: Software, 
Extensions: AL_EXT_OFFSET AL_EXT_LINEAR_DISTANCE AL_EXT_EXPONENT_DISTANCE AL_EXT_float32 AL_EXT_STATIC_BUFFER AL_EXT_SOURCE_NOTIFICATIONS AL_EXT_SOURCE_SPATIALIZATION, 
ALC Version: 1.1, 
ALC Extensions: ALC_EXT_CAPTURE ALC_ENUMERATION_EXT ALC_EXT_MAC_OSX ALC_EXT_ASA ALC_EXT_ASA_DISTORTION ALC_EXT_ASA_ROGER_BEEP
Available devices: 
Available capture devices: 
  Corsair VOID Wireless Gaming Dongle
Unhandled exception. System.TypeInitializationException: The type initializer for 'OpenToolkit.Audio.OpenAL.Extensions.Creative.EFX.EFX' threw an exception.
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'ptr')
   at System.Runtime.InteropServices.Marshal.GetDelegateForFunctionPointer(IntPtr ptr, Type t)
   at System.Runtime.InteropServices.Marshal.GetDelegateForFunctionPointer[TDelegate](IntPtr ptr)
   at OpenToolkit.Audio.OpenAL.ApiContainer`1.LoadDelegate[TDelegate](String name) in /Users/[username]/opentk/src/OpenAL/OpenToolkit.OpenAL/Native/ApiContainer.cs:line 54
   at OpenToolkit.Audio.OpenAL.Extensions.Creative.EFX.EFX..cctor() in /Users/[username]/opentk/src/OpenAL/OpenToolkit.OpenAL/Extensions/Creative.EFX/EFX.cs:line 137
   --- End of inner exception stack trace ---
   at OpenToolkit.Audio.OpenAL.Extensions.Creative.EFX.EFX.IsExtensionPresent(ALDevice device) in /Users/[username]/opentk/src/OpenAL/OpenToolkit.OpenAL/Extensions/Creative.EFX/EFX.cs:line 42
   at OpenToolkit.Audio.OpenAL.ALTest.Main() in /Users/[username]/opentk/OpenALTest/ALTest.cs:line 64
```

**Comment by haiyaku365** [comment]
Can you try replace
/opentk/OpenALTest/ALTest.cs:line 30
`var device = ALC.OpenDevice(deviceName);`
with
`var device = ALC.OpenDevice("");`
and run again?

**Comment by stabbyderg** [comment]
Done:
```
Hello!
Devices: Built-in Output
All Devices: 
ALError at 'Start': Invalid Value
Attributes: , , , , , 
Vendor: Apple Computer Inc., 
Version: 1.1, 
Renderer: Software, 
Extensions: AL_EXT_OFFSET AL_EXT_LINEAR_DISTANCE AL_EXT_EXPONENT_DISTANCE AL_EXT_float32 AL_EXT_STATIC_BUFFER AL_EXT_SOURCE_NOTIFICATIONS AL_EXT_SOURCE_SPATIALIZATION, 
ALC Version: 1.1, 
ALC Extensions: ALC_EXT_CAPTURE ALC_ENUMERATION_EXT ALC_EXT_MAC_OSX ALC_EXT_ASA ALC_EXT_ASA_DISTORTION ALC_EXT_ASA_ROGER_BEEP
Available devices: 
Available capture devices: 
  Built-in Microphone
Unhandled exception. System.TypeInitializationException: The type initializer for 'OpenToolkit.Audio.OpenAL.Extensions.Creative.EFX.EFX' threw an exception.
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'ptr')
   at System.Runtime.InteropServices.Marshal.GetDelegateForFunctionPointer(IntPtr ptr, Type t)
   at System.Runtime.InteropServices.Marshal.GetDelegateForFunctionPointer[TDelegate](IntPtr ptr)
   at OpenToolkit.Audio.OpenAL.ApiContainer`1.LoadDelegate[TDelegate](String name) in /Users/[username]/opentk/src/OpenAL/OpenToolkit.OpenAL/Native/ApiContainer.cs:line 54
   at OpenToolkit.Audio.OpenAL.Extensions.Creative.EFX.EFX..cctor() in /Users/[username]/opentk/src/OpenAL/OpenToolkit.OpenAL/Extensions/Creative.EFX/EFX.cs:line 137
   --- End of inner exception stack trace ---
   at OpenToolkit.Audio.OpenAL.Extensions.Creative.EFX.EFX.IsExtensionPresent(ALDevice device) in /Users/[username]/opentk/src/OpenAL/OpenToolkit.OpenAL/Extensions/Creative.EFX/EFX.cs:line 42
   at OpenToolkit.Audio.OpenAL.ALTest.Main() in /Users/[username]/opentk/OpenALTest/ALTest.cs:line 64
```

**Comment by haiyaku365** [comment]
Look like OpenAl can't even create context with default device.
Can you confirm that audio out default device is available?

and maybe change 
`Console.WriteLine("Hello!");`
to
`Console.WriteLine("Helloooo!!!!!");`
to see if code change really effective.

**Comment by stabbyderg** [comment]
Changing code does seem to work:
`Helloooo!!!!!!!!!!!!!!
Devices: Built-in Output
All Devices: 
ALError at 'Start': Invalid Value
Attributes: , , , , , 
Vendor: Apple Computer Inc., 
Version: 1.1, 
Renderer: Software, 
`

The audio out device does work; can play anything else on my system with it...

**Comment by haiyaku365** [comment]
I have no idea why it's not work.

we are not try openal-soft with default device yet.
please try openal-soft with `var device = ALC.OpenDevice("");` code

**Comment by haiyaku365** [comment]
Look like openal-soft have `openal-info` tool you can run in terminal.
I will look into the [code](https://github.com/kcat/openal-soft/blob/master/utils/openal-info.c).

**Comment by stabbyderg** [comment]
I can find openal-info but just typing in openal-info or ./openal-info doesn't seem to work:

```
openal-info
-bash: openal-info: command not found

./openal-info
dyld: Library not loaded: @rpath/libopenal.1.dylib
  Referenced from: /usr/local/Cellar/openal-soft/1.20.1/bin/./openal-info
  Reason: image not found
Abort trap: 6
```

**Comment by haiyaku365** [comment]
on [quick search](https://duckduckgo.com/?q=dyld%3A+Library+not+loaded%3A+Reason%3A+image+not+found) you might need to run
```
brew cleanup
brew update
brew upgrade
brew cleanup
```

**Comment by haiyaku365** [comment]
if openal-info can open device than 
-`var device = ALC.OpenDevice(deviceName);`
+`var device = ALC.OpenDevice(null);` 
should work.

But unfortunately It will only use default device set by system.

**Comment by stabbyderg** [comment]
Still getting the 'image not found' error when I try to run ./openal-info.

Changing var device = ALC.OpenDevice(null); still outputs the same error message.

**Comment by haiyaku365** [comment]
[OSX: openal-info don't work](https://github.com/kcat/openal-soft/issues/153)

😵

Maybe try with openal-soft v1.19.1

```
brew install openal-soft@1.19.1
brew switch openal-soft 1.19.1
brew info openal-soft
```

**Comment by haiyaku365** [comment]
With [v0.5.0.0](https://github.com/haiyaku365/StimmingSignalGenerator/releases/tag/v0.5.0.0) using PortAudio instead of OpenAL it might work.
